// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJYBV6qiUmqoMkPmuVuWLJ9bsCw0O7Jw',
    appId: '1:1097240028252:web:a33ac37ee28952442d3299',
    messagingSenderId: '1097240028252',
    projectId: 'cura-8d85c',
    authDomain: 'cura-8d85c.firebaseapp.com',
    storageBucket: 'cura-8d85c.firebasestorage.app',
    measurementId: 'G-XB98ZJ1NQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGZ6g7lk3QoVyxRjyIENc7yGQSRhEO8U',
    appId: '1:1097240028252:android:ebc6aa1b8fad19ff2d3299',
    messagingSenderId: '1097240028252',
    projectId: 'cura-8d85c',
    storageBucket: 'cura-8d85c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLfclE8PFrV1wQ2uaMMmTGOkTsnbmh1q8',
    appId: '1:1097240028252:ios:a3b03660a7b0eb412d3299',
    messagingSenderId: '1097240028252',
    projectId: 'cura-8d85c',
    storageBucket: 'cura-8d85c.firebasestorage.app',
    iosBundleId: 'com.app.cura',
  );
}
